load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

# http_archive(
#   name = "io_bazel_rules_ros",
#   strip_prefix = "rules_ros-dbff200ff9b1eedbf42f4ccee6a32f39903eca1f",
#   sha256 = "250ed53b426c5c3e85862da0e7cd73887cf051b5730116d00c27b63ee5a73afc",
#   urls = [
#     "http://git.gs-robot.com/bazel-build/rules_ros/-/archive/dbff200ff9b1eedbf42f4ccee6a32f39903eca1f/rules_ros-dbff200ff9b1eedbf42f4ccee6a32f39903eca1f.tar.gz",
#   ],
# )
# load("@io_bazel_rules_ros//ros:ros.bzl", "ros_deps")
# ros_deps()

http_archive(
    name = "com_github_gflags_gflags",
    sha256 = "34af2f15cf7367513b352bdcd2493ab14ce43692d2dcd9dfc499492966c64dcf",
    strip_prefix = "gflags-2.2.2",
    urls = ["https://github.com/gflags/gflags/archive/v2.2.2.tar.gz"],
)

http_archive(
    name = "com_github_google_glog",
    sha256 = "21bc744fb7f2fa701ee8db339ded7dce4f975d0d55837a97be7d46e8382dea5a",
    strip_prefix = "glog-0.5.0",
    urls = ["https://github.com/google/glog/archive/v0.5.0.zip"],
)

# local_repository(
#   name = "rosdep_lib",
#   path = "/opt/ros/kinetic/",
# )

new_local_repository(
    name = "rosdep",
    path = "/opt/ros/kinetic",
    build_file = "BUILD.rosdep",
)